name: eden-emulator
base: core24
version: '0.1.0'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
summary: Eden, Switch Emulator
description: |
  An open-source Switch emulator, forked from the Yuzu emulator
grade: stable
confinement: strict
compression: lzo

apps:
  eden-emulator:
    command-chain: [desktop-launch-eden]
    command: usr/bin/eden
    desktop: usr/share/applications/dev.eden_emu.eden.desktop
    common-id: dev.eden_emu.eden
    environment:
      QT_QPA_PLATFORMTHEME: xdgdesktopportal
      LD_LIBRARY_PATH: $SNAP/lxqt-support-core24/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/lxqt-support-core24/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
    extensions: [kde-neon-6]
    plugs:
      - screen-inhibit-control
      - home
      - removable-media
      - mount-observe
      - system-observe
      - joystick
      - bluez
      - udisks2

plugs:
  shared-memory:
    private: true
  lxqt-support-core24:
    content: lxqt-support-core24
    interface: content
    target: $SNAP/lxqt-support-core24
    default-provider: lxqt-support-core24

layout:
  /usr/share/color-schemes:
    symlink: $SNAP/lxqt-support-core24/usr/share/color-schemes
  /usr/share/Kvantum:
    symlink: $SNAP/lxqt-support-core24/usr/share/Kvantum

parts:
  eden-emulator-app:
    plugin: dump
    source:
      - on amd64: https://github.com/eden-emulator/Releases/releases/download/v$SNAPCRAFT_PROJECT_VERSION/Eden-Ubuntu-24.04-v$SNAPCRAFT_PROJECT_VERSION-amd64.deb
      - on arm64: https://github.com/eden-emulator/Releases/releases/download/v$SNAPCRAFT_PROJECT_VERSION/Eden-Ubuntu-24.04-v$SNAPCRAFT_PROJECT_VERSION-aarch64.deb
    override-build: |
      craftctl default
      sed -i 's|Name=Eden|Name=Eden [Kyu]|' $CRAFT_PART_INSTALL/usr/share/applications/dev.eden_emu.eden.desktop
      sed -i 's|Icon=dev.eden_emu.eden|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/dev.eden_emu.eden.svg|' $CRAFT_PART_INSTALL/usr/share/applications/dev.eden_emu.eden.desktop

  dependencies:
    after: [eden-emulator-app]
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libzydis4.0t64
      - libcpp-httplib0.14t64
      - libcubeb0
      - libdiscord-rpc3
      - libenet7
      - libquazip1-qt6-1t64
      - libsimpleini1t64
      - libdecor-0-0
      - libjack0
      - libfmt9
      - libboost-context1.83.0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libSDL2-2.0.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libZydis.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libcpp-httplib.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libcubeb.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdiscord-rpc.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libenet.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libquazip1-qt6.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsimpleini.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdecor-0.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libjack.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libfmt.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libboost_context.so*

  other-files:
    after: [dependencies]
    plugin: dump
    source: ./other-files
    prime:
      - desktop-launch-eden